# config/cucumber.yml
##YAML Template
---
android: RESET_BETWEEN_SCENARIOS=1 PLATFORM=android -r features/support -r features/android/support -r features/step_definitions -r features/android/pages
ios:    RESET_BETWEEN_SCENARIOS=1 PLATFORM=ios SDK_VERSION=7.0 -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages
